# This file was generated by GoReleaser. DO NOT EDIT.
cask "velocity" do
  version "0.21.57"

  on_macos do
    on_intel do
      sha256 "0d562ba63e84b3e892cc7732c17e425dde503eb870fa0f73b26e67c685ac5907"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-darwin-amd64.tar.gz",
        verified: "github.com/velocitykode/velocity-installer/"
    end
    on_arm do
      sha256 "e76c32b24a2544de363110b9cee420a69761d016bad28da9b3d3508de501eaf5"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-darwin-arm64.tar.gz",
        verified: "github.com/velocitykode/velocity-installer/"
    end
  end

  on_linux do
    on_intel do
      sha256 "54ffbf90b147cb8092c7522ac2cfb7d82fb080980cfb87abd987d48a689e17bd"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-linux-amd64.tar.gz",
        verified: "github.com/velocitykode/velocity-installer/"
    end
    on_arm do
      sha256 "853f57b8be1ba4ae1613b5f0b34f735b15bccc1287ab988be37c33ce41cd927a"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-linux-arm64.tar.gz",
        verified: "github.com/velocitykode/velocity-installer/"
    end
  end

  name "velocity"
  desc "Installer for the Velocity Go web framework"
  homepage "https://github.com/velocitykode/velocity-installer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "velocity"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/velocity"]
    end
  end

  # No zap stanza required

end
