# This file was generated by GoReleaser. DO NOT EDIT.
cask "velocity" do
  version "0.21.76"

  on_macos do
    on_arm do
      sha256 "fbf513a7f1d880209e0b70530ddc0aa4f2de476d7c541e71053a0e5b80a0175f"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "31cb440dd06375e368dc48d9010e6c760c21fdd6f2812f4130ba380736d14d86"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3343949d4fa1e45393884e5fe9e0354804d1b3c85feb0cf1b4ab5daffcaca4c"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "c272da5a0b1d23ae86527564596a0fe3baef47f0c0fdc0ac33012d3f95e40d35"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-linux-amd64.tar.gz"
    end
  end

  name "velocity"
  desc "Installer for the Velocity Go web framework"
  homepage "https://github.com/velocitykode/velocity-installer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "velocity"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/velocity"]
    end
  end

  # No zap stanza required
end
