# This file was generated by GoReleaser. DO NOT EDIT.
cask "velocity" do
  version "0.22.16"

  on_macos do
    on_arm do
      sha256 "79a45641d556ad6a1f9cee4a74da475a2e6a29be042c8984f46e847c282b03b0"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "724e3a740b0362d8b987b64c070cba18c23f5dce002d24a0f2bda946ad062c81"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4d8475e523017d3ff0370b5faab0214c7a2082aa428e510b6d1e157471b2b140"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "c8d92f28ca73dc1de14361c013823197894f3337f1543cf63693bc531a66d3ea"
      url "https://github.com/velocitykode/velocity-installer/releases/download/v#{version}/velocity-linux-amd64.tar.gz"
    end
  end

  name "velocity"
  desc "Installer for the Velocity Go web framework"
  homepage "https://github.com/velocitykode/velocity-installer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "velocity"
  binary "vel"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/velocity", "#{staged_path}/vel"]
    end
  end

  # No zap stanza required
end
