# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Velocity < Formula
  desc "CLI for the Velocity Go web framework"
  homepage "https://github.com/velocitykode/velocity-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/velocitykode/velocity-cli/releases/download/v0.5.0/velocity-darwin-amd64.tar.gz"
      sha256 "0035a77a1448b32f4f88a0394d58e8e1773546a3b5811a11a03432861c8ac4d9"

      def install
        if Hardware::CPU.arm?
          bin.install "velocity-darwin-arm64" => "velocity"
        else
          bin.install "velocity-darwin-amd64" => "velocity"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/velocitykode/velocity-cli/releases/download/v0.5.0/velocity-darwin-arm64.tar.gz"
      sha256 "66cef5a94075c4f1afccdc0ad15e7423eba7b47f328bf7aa7b090b35fd7afad3"

      def install
        if Hardware::CPU.arm?
          bin.install "velocity-darwin-arm64" => "velocity"
        else
          bin.install "velocity-darwin-amd64" => "velocity"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/velocitykode/velocity-cli/releases/download/v0.5.0/velocity-linux-amd64.tar.gz"
      sha256 "560222156dd95457be07e28bcfd30f321c6df010b713a4adfcacc525f9523177"
      def install
        if Hardware::CPU.arm?
          bin.install "velocity-darwin-arm64" => "velocity"
        else
          bin.install "velocity-darwin-amd64" => "velocity"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/velocitykode/velocity-cli/releases/download/v0.5.0/velocity-linux-arm64.tar.gz"
      sha256 "beca585e653ecc33d4bb899ee9dba0e3264c9af3f163357d0426c9a683c4f188"
      def install
        if Hardware::CPU.arm?
          bin.install "velocity-darwin-arm64" => "velocity"
        else
          bin.install "velocity-darwin-amd64" => "velocity"
        end
      end
    end
  end

  test do
    assert_match "VELOCITY CLI", shell_output("#{bin}/velocity version")
  end
end
