# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Velocity < Formula
  desc "CLI for the Velocity Go web framework"
  homepage "https://github.com/velocitykode/velocity-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/velocitykode/velocity-cli/releases/download/v0.4.1/velocity-darwin-amd64.tar.gz"
      sha256 "c3b7f4744a5a6253b304c6f5b42da91e62f823456647b633850c7bcc9532755f"

      def install
        if Hardware::CPU.arm?
          bin.install "velocity-darwin-arm64" => "velocity"
        else
          bin.install "velocity-darwin-amd64" => "velocity"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/velocitykode/velocity-cli/releases/download/v0.4.1/velocity-darwin-arm64.tar.gz"
      sha256 "5b8dac16de470f8d59517e9e1a769a99b6e9535d0048cfeb4f3c2937e243286a"

      def install
        if Hardware::CPU.arm?
          bin.install "velocity-darwin-arm64" => "velocity"
        else
          bin.install "velocity-darwin-amd64" => "velocity"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/velocitykode/velocity-cli/releases/download/v0.4.1/velocity-linux-amd64.tar.gz"
      sha256 "c9f120ab7d4181f6f77bc7060072dc0bc9736a7597dae9480729c5e3b959e9ff"
      def install
        if Hardware::CPU.arm?
          bin.install "velocity-darwin-arm64" => "velocity"
        else
          bin.install "velocity-darwin-amd64" => "velocity"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/velocitykode/velocity-cli/releases/download/v0.4.1/velocity-linux-arm64.tar.gz"
      sha256 "106fd45b001f24fafc7a2a299ce1ff3a9919b25fb6b40ea2a5c3cb925efc9771"
      def install
        if Hardware::CPU.arm?
          bin.install "velocity-darwin-arm64" => "velocity"
        else
          bin.install "velocity-darwin-amd64" => "velocity"
        end
      end
    end
  end

  test do
    assert_match "VELOCITY CLI", shell_output("#{bin}/velocity version")
  end
end
